"""
Reporter Module - Generate structured reports from findings.
"""

import json
import os
from datetime import datetime

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich import box

try:
    from jinja2 import Template
    HAS_JINJA = True
except ImportError:
    HAS_JINJA = False


# HTML report template
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PENT Security Report - {{ target }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
  .container { max-width: 960px; margin: 0 auto; padding: 2rem; }
  h1 { color: #58a6ff; margin-bottom: 0.5rem; }
  h2 { color: #79c0ff; margin: 2rem 0 1rem; border-bottom: 1px solid #21262d; padding-bottom: 0.5rem; }
  h3 { color: #d2a8ff; margin: 1rem 0 0.5rem; }
  .meta { color: #8b949e; margin-bottom: 2rem; }
  .disclaimer { background: #3d1f00; border: 1px solid #9e6a03; padding: 1rem; border-radius: 6px; margin: 1rem 0; }
  .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
  .stat { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; text-align: center; }
  .stat .num { font-size: 2rem; font-weight: bold; }
  .critical { color: #f85149; }
  .high { color: #f0883e; }
  .medium { color: #d29922; }
  .low { color: #3fb950; }
  .info { color: #8b949e; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th { background: #161b22; padding: 0.75rem; text-align: left; border: 1px solid #30363d; }
  td { padding: 0.75rem; border: 1px solid #30363d; }
  tr:nth-child(even) { background: #161b22; }
  .badge { padding: 2px 8px; border-radius: 12px; font-size: 0.8rem; font-weight: bold; }
  .badge.critical { background: #3d0a0a; border: 1px solid #f85149; }
  .badge.high { background: #3d1d00; border: 1px solid #f0883e; }
  .badge.medium { background: #3d2e00; border: 1px solid #d29922; }
  .badge.low { background: #0a3d0a; border: 1px solid #3fb950; }
  .badge.info { background: #1c2028; border: 1px solid #8b949e; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #21262d; color: #8b949e; font-size: 0.9rem; }
</style>
</head>
<body>
<div class="container">
  <h1>PENT Security Assessment Report</h1>
  <div class="meta">
    <strong>Target:</strong> {{ target }}<br>
    <strong>Date:</strong> {{ date }}<br>
    <strong>Tester:</strong> {{ tester }}
  </div>

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This report was generated during an authorized security assessment.
    All testing was performed with proper authorization. Findings should be validated and
    remediated according to organizational risk tolerance.
  </div>

  <h2>Executive Summary</h2>
  <div class="stats">
    <div class="stat"><div class="num critical">{{ counts.critical }}</div>Critical</div>
    <div class="stat"><div class="num high">{{ counts.high }}</div>High</div>
    <div class="stat"><div class="num medium">{{ counts.medium }}</div>Medium</div>
    <div class="stat"><div class="num low">{{ counts.low }}</div>Low</div>
    <div class="stat"><div class="num info">{{ counts.info }}</div>Info</div>
  </div>
  <p>Total findings: <strong>{{ total }}</strong></p>

  <h2>Findings</h2>
  <table>
    <thead>
      <tr><th>#</th><th>Severity</th><th>Category</th><th>Title</th><th>Detail</th></tr>
    </thead>
    <tbody>
    {% for f in findings %}
      <tr>
        <td>{{ loop.index }}</td>
        <td><span class="badge {{ f.severity }}">{{ f.severity | upper }}</span></td>
        <td>{{ f.get('category', 'General') }}</td>
        <td>{{ f.get('title', f.get('key', 'N/A')) }}</td>
        <td>{{ f.get('detail', f.get('value', 'N/A')) }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h2>Recommendations</h2>
  <ul>
  {% for r in recommendations %}
    <li><strong>{{ r.title }}:</strong> {{ r.detail }}</li>
  {% endfor %}
  </ul>

  <footer>
    Generated by PENT - Penetration Testing Assistant<br>
    Report generated on {{ date }}
  </footer>
</div>
</body>
</html>"""


class ReporterModule:
    """Generate security assessment reports."""

    def __init__(self, console: Console):
        self.console = console
        self.findings = []
        self.target = ""
        self.tester = ""

    def add_findings(self, findings: list):
        """Add findings from other modules."""
        self.findings.extend(findings)

    def _count_severities(self) -> dict:
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in self.findings:
            sev = f.get("severity", "info").lower()
            if sev in counts:
                counts[sev] += 1
            else:
                counts["info"] += 1
        return counts

    def _generate_recommendations(self) -> list:
        """Generate recommendations based on findings."""
        recs = []
        seen_cats = set()

        rec_map = {
            "missing_header": {
                "title": "Add Security Headers",
                "detail": "Configure web server to include security headers: Content-Security-Policy, "
                          "Strict-Transport-Security, X-Content-Type-Options, X-Frame-Options, Referrer-Policy.",
            },
            "info_disclosure": {
                "title": "Remove Information Disclosure Headers",
                "detail": "Remove or obfuscate Server, X-Powered-By, and other technology-revealing headers.",
            },
            "CORS": {
                "title": "Fix CORS Configuration",
                "detail": "Restrict Access-Control-Allow-Origin to specific trusted domains. Never use wildcard (*) "
                          "with credentials.",
            },
            "XSS": {
                "title": "Remediate Cross-Site Scripting",
                "detail": "Implement input validation and output encoding. Deploy Content-Security-Policy header. "
                          "Use frameworks that auto-escape by default.",
            },
            "SQLi": {
                "title": "Fix SQL Injection Vulnerabilities",
                "detail": "Use parameterized queries/prepared statements. Implement input validation. "
                          "Apply principle of least privilege to database accounts.",
            },
            "CSRF": {
                "title": "Implement CSRF Protection",
                "detail": "Add anti-CSRF tokens to all state-changing forms. Set SameSite cookie attribute. "
                          "Validate Origin/Referer headers.",
            },
            "Path Traversal": {
                "title": "Fix Path Traversal Vulnerabilities",
                "detail": "Validate and sanitize file path inputs. Use allowlists for permitted files. "
                          "Avoid passing user input to file system operations.",
            },
            "Cookie Security": {
                "title": "Secure Cookie Configuration",
                "detail": "Set Secure, HttpOnly, and SameSite flags on all sensitive cookies.",
            },
            "ssl": {
                "title": "Strengthen TLS Configuration",
                "detail": "Disable TLS 1.0/1.1. Enable TLS 1.3. Use strong cipher suites. "
                          "Ensure HSTS is configured with adequate max-age.",
            },
        }

        for f in self.findings:
            cat = f.get("category", f.get("title", ""))
            for key, rec in rec_map.items():
                if key.lower() in cat.lower() and key not in seen_cats:
                    recs.append(rec)
                    seen_cats.add(key)

        if not recs:
            recs.append({
                "title": "Continue Security Testing",
                "detail": "Perform regular security assessments and keep systems up to date.",
            })

        return recs

    # ------------------------------------------------------------------
    # Markdown report
    # ------------------------------------------------------------------
    def generate_markdown(self, output_dir: str) -> str:
        """Generate a Markdown report."""
        counts = self._count_severities()
        recs = self._generate_recommendations()
        date = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            f"# PENT Security Assessment Report",
            f"",
            f"**Target:** {self.target}  ",
            f"**Date:** {date}  ",
            f"**Tester:** {self.tester}  ",
            f"",
            f"> **Disclaimer:** This report was generated during an authorized security assessment.",
            f"",
            f"## Executive Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| Critical | {counts['critical']} |",
            f"| High     | {counts['high']} |",
            f"| Medium   | {counts['medium']} |",
            f"| Low      | {counts['low']} |",
            f"| Info     | {counts['info']} |",
            f"| **Total**| **{len(self.findings)}** |",
            f"",
            f"## Findings",
            f"",
            f"| # | Severity | Title | Detail |",
            f"|---|----------|-------|--------|",
        ]

        for i, f in enumerate(self.findings, 1):
            sev = f.get("severity", "info").upper()
            title = f.get("title", f.get("key", "N/A"))
            detail = f.get("detail", f.get("value", "N/A"))
            lines.append(f"| {i} | {sev} | {title} | {detail} |")

        lines.extend([
            f"",
            f"## Recommendations",
            f"",
        ])
        for r in recs:
            lines.append(f"- **{r['title']}:** {r['detail']}")

        lines.extend([
            f"",
            f"---",
            f"*Generated by PENT - Penetration Testing Assistant on {date}*",
        ])

        content = "\n".join(lines)
        os.makedirs(output_dir, exist_ok=True)
        filename = f"pent_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as fh:
            fh.write(content)

        return filepath

    # ------------------------------------------------------------------
    # HTML report
    # ------------------------------------------------------------------
    def generate_html(self, output_dir: str) -> str:
        """Generate an HTML report."""
        if not HAS_JINJA:
            self.console.print("[yellow]jinja2 not installed. Falling back to Markdown.[/yellow]")
            return self.generate_markdown(output_dir)

        counts = self._count_severities()
        recs = self._generate_recommendations()
        date = datetime.now().strftime("%Y-%m-%d %H:%M")

        template = Template(HTML_TEMPLATE)
        html = template.render(
            target=self.target,
            date=date,
            tester=self.tester,
            counts=counts,
            total=len(self.findings),
            findings=self.findings,
            recommendations=recs,
        )

        os.makedirs(output_dir, exist_ok=True)
        filename = f"pent_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as fh:
            fh.write(html)

        return filepath

    # ------------------------------------------------------------------
    # JSON report
    # ------------------------------------------------------------------
    def generate_json(self, output_dir: str) -> str:
        """Generate a JSON report."""
        counts = self._count_severities()
        recs = self._generate_recommendations()
        date = datetime.now().strftime("%Y-%m-%d %H:%M")

        report = {
            "meta": {
                "tool": "PENT",
                "target": self.target,
                "date": date,
                "tester": self.tester,
                "total_findings": len(self.findings),
            },
            "summary": counts,
            "findings": self.findings,
            "recommendations": recs,
        }

        os.makedirs(output_dir, exist_ok=True)
        filename = f"pent_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as fh:
            json.dump(report, fh, indent=2)

        return filepath

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------
    def run(self, output_dir: str = "reports", fmt: str = "md"):
        """Generate report in specified format."""
        generators = {
            "md": self.generate_markdown,
            "html": self.generate_html,
            "json": self.generate_json,
        }

        gen = generators.get(fmt, self.generate_markdown)
        filepath = gen(output_dir)
        self.console.print(f"[bold green]Report saved: {filepath}[/bold green]")
        return filepath

    # ------------------------------------------------------------------
    # Interactive
    # ------------------------------------------------------------------
    def interactive(self):
        """Interactive report generation."""
        self.console.print(Panel("[bold]Report Generator[/bold]", border_style="cyan"))

        if not self.findings:
            self.console.print("[yellow]No findings collected yet. Run some scans first.[/yellow]")
            add_manual = Confirm.ask("Add a manual finding?")
            if add_manual:
                sev = Prompt.ask("Severity", choices=["critical", "high", "medium", "low", "info"])
                title = Prompt.ask("Title")
                detail = Prompt.ask("Detail")
                self.findings.append({
                    "timestamp": datetime.now().isoformat(),
                    "severity": sev,
                    "title": title,
                    "detail": detail,
                })
            else:
                return

        self.target = Prompt.ask("Target name", default=self.target or "unknown")
        self.tester = Prompt.ask("Tester name", default=self.tester or "Security Tester")

        fmt = Prompt.ask("Report format", choices=["md", "html", "json"], default="md")
        output_dir = Prompt.ask("Output directory", default="reports")

        filepath = self.run(output_dir=output_dir, fmt=fmt)
        self.console.print(f"\n[bold green]Report generated: {filepath}[/bold green]")
